### ISSUE TITLE
Submission checklist

### ISSUE THREAD

**Issue by kevinwang09** [PYangLab/Cepo#1]
- [x] Parallisation under the DelayedArray framework
- [x] README
- [x] Write at least one vignette
- [x] Code coverage using `codecov` (only activate if repo is public)
- [x] `formatR`
- [x] Proof-reading
- [ ] Submission to BioC
- [x] Twitter advertising
